name: "pre-release"

on:
  push:
    branches:
      - "master"

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  pre-release:
    name: "Pre-Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: 'recursive'

      - name: Download Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Install VSCode extension package
        run: bun install @vscode/vsce

      - name: Build
        run: bun run build

      - name: Get version identifiers
        run: |
          echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
          echo "SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Create extension file
        run: bun x @vscode/vsce package -o basalt-vscode-${{ env.DATE }}-${{ env.SHA }}.vsix

      - name: Create release
        run: |
          gh release create pre-release-${{ env.DATE }}-${{ env.SHA }} \
            basalt-vscode-${{ env.DATE }}-${{ env.SHA }}.vsix \
            --title "Pre-Release ${{ env.DATE }} (${{ env.SHA }})" \
            --prerelease \
            --generate-notes